In [32]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LinearRegression
import pickle
from sklearn.tree import DecisionTreeRegressor

In [33]:
data = pd.read_csv('3D_spatial_network.txt',delimiter=',')

df = pd.DataFrame(data)
df_columns = ['OSM_ID','LONGITUDE','LATITUDE','ALTITUDE']
df.columns = df_columns
#df.shape
#data.head()
df.head()

OSM_ID  LONGITUDE   LATITUDE   ALTITUDE
0  144552912   9.350188  56.740679  17.614840
1  144552912   9.350549  56.740544  18.083536
2  144552912   9.350806  56.740484  18.279465
3  144552912   9.351053  56.740486  18.422974
4  144552912   9.351475  56.740502  19.124889

In [34]:
X = df.ix[:,1:3]
y = df.ix[:,3]
X.head(),y.head()

(   LONGITUDE   LATITUDE
 0   9.350188  56.740679
 1   9.350549  56.740544
 2   9.350806  56.740484
 3   9.351053  56.740486
 4   9.351475  56.740502, 0    17.614840
 1    18.083536
 2    18.279465
 3    18.422974
 4    19.124889
 Name: ALTITUDE, dtype: float64)

In [35]:
X_train , X_test , y_train ,y_test = train_test_split(X,y)

In [36]:
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.fit_transform(X_test)

X_train_std[0:3]

array([[-1.50695137, -1.09576753],
       [ 0.51871513,  1.29716792],
       [-2.27614445, -0.67714159]])

In [38]:
#reg = LinearRegression(n_jobs=-1,normalize=False)
reg1 = DecisionTreeRegressor()
reg1.fit(X_train_std,y_train,)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_split=1e-07,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, presort=False, random_state=None,
           splitter='best')

In [39]:
y_pred = reg.predict(X_test_std)

In [40]:
y_test_std = y_test.as_matrix()
y_test_std[0:6],y_pred[0:6]

(array([  0.29368612,  38.82108156,  21.5039346 ,  11.62180932,
          6.28321237,  30.39221419]),
 array([ 20.26883541,  24.37922246,  25.1408253 ,  20.59056481,
         22.49749261,  23.22424049]))

In [41]:
u = ((y_test - y_pred) ** 2).sum()
v = ((y_test - y_test.mean()) ** 2).sum()
score = (1 - u/v)
score*100

2.772921487227098

In [44]:
with open('3D_space.pickle','wb') as f:
    pickle.dump(reg1,f)