In [122]:
import numpy as np
import pandas as pd
import xlrd
from sklearn.linear_model import LinearRegression
import random
from sklearn.preprocessing import StandardScaler
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score
import pickle

In [123]:
df = pd.read_excel('AirQualityUCI.xlsx')
df.head()

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  \
0 2004-03-10  18:00:00     2.6      1360.00       150  11.881723   
1 2004-03-10  19:00:00     2.0      1292.25       112   9.397165   
2 2004-03-10  20:00:00     2.2      1402.00        88   8.997817   
3 2004-03-10  21:00:00     2.2      1375.50        80   9.228796   
4 2004-03-10  22:00:00     1.6      1272.25        51   6.518224   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0        1045.50    166.0       1056.25    113.0       1692.00      1267.50   
1         954.75    103.0       1173.75     92.0       1558.75       972.25   
2         939.25    131.0       1140.00    114.0       1554.50      1074.00   
3         948.25    172.0       1092.00    122.0       1583.75      1203.25   
4         835.50    131.0       1205.00    116.0       1490.00      1110.00   

       T         RH        AH  
0  13.60  48.875001  0.757754  
1  13.30  47.700000  0.725487  
2  11.90  53.975000  0.750239  
3  11.00  60.000000  0.786713  
4  11.15  59.575001  0.788794

In [124]:
df.shape

(9357, 15)

In [125]:
#df1['Date'] = df['Date'.str.extract('(...-..-..)')

In [126]:
#'CO(GT)-PT08.S5(O3)RH-AH'
#x1 = df.filter(regex='[CO(GT)-PT08.S5(O3)]')
x_part1 = df.ix[:,2:12]
x_part2 = df.ix[:,13:15]

x_part2.head()
X = pd.concat([x_part1,x_part2],axis=1)
X.head()

CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  \
0     2.6      1360.00       150  11.881723        1045.50    166.0   
1     2.0      1292.25       112   9.397165         954.75    103.0   
2     2.2      1402.00        88   8.997817         939.25    131.0   
3     2.2      1375.50        80   9.228796         948.25    172.0   
4     1.6      1272.25        51   6.518224         835.50    131.0   

   PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)         RH        AH  
0       1056.25    113.0       1692.00      1267.50  48.875001  0.757754  
1       1173.75     92.0       1558.75       972.25  47.700000  0.725487  
2       1140.00    114.0       1554.50      1074.00  53.975000  0.750239  
3       1092.00    122.0       1583.75      1203.25  60.000000  0.786713  
4       1205.00    116.0       1490.00      1110.00  59.575001  0.788794

In [127]:
y = df.ix[:,12:13]
y.head()

T
0  13.60
1  13.30
2  11.90
3  11.00
4  11.15

In [128]:
    X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2)

In [129]:
sc = StandardScaler()

sc.fit(X_train)

X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

X_train_std[1:3]

array([[-2.13531886,  0.95843954, -0.29376284,  0.28284565,  0.6137884 ,
        -1.42403201,  0.10875572, -2.02411947,  0.67554137,  0.04147936,
        -0.25889165,  0.19593737],
       [ 0.47403689, -1.05136746, -0.29376284,  0.03942798, -0.61011792,
         0.18357652,  1.29457298,  0.46708526, -1.4162029 , -0.72630235,
        -0.44559281,  0.17917471]])

In [130]:
reg = LinearRegression()

reg.fit(X_train_std,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [131]:
y_pred = reg.predict(X_test_std)
y_pred

array([[ 29.79138453],
       [  4.68061447],
       [ 22.21808747],
       ..., 
       [ 19.68402903],
       [  8.5718085 ],
       [ 11.25823221]])

In [132]:
#reg.score(y_test,y_pred)
y_test.shape,y_pred.shape

((1872, 1), (1872, 1))

In [133]:
y_test.head(),y_pred[0:5]

(           T
 2138  27.025
 6058   6.350
 3972  21.125
 5775  15.925
 7154   8.300, array([[ 29.79138453],
        [  4.68061447],
        [ 22.21808747],
        [ 13.94391851],
        [  7.45261495]]))

In [134]:
y_test_std = y_test.as_matrix()
y_test_std[0:5],y_pred[0:5]

(array([[ 27.0250001 ],
        [  6.35000002],
        [ 21.125     ],
        [ 15.92500019],
        [  8.30000019]]), array([[ 29.79138453],
        [  4.68061447],
        [ 22.21808747],
        [ 13.94391851],
        [  7.45261495]]))

In [135]:
#accu = accuracy_score(y_test_std,y_pred)
#score_reg = reg.score(y_test_std,y_pred)

In [136]:
u = ((y_test_std - y_pred) ** 2).sum()
v = ((y_test_std - y_test_std.mean()) ** 2).sum()
score = (1 - u/v)
score

0.99517271926745099

In [137]:
with open('AirQuality_regression.pickle','wb') as f:
    pickle.dump(reg,f)