In [92]:
from __future__ import print_function
import matplotlib.pyplot as plt
import numpy as np
import os
import sys
import tarfile
from IPython.display import display,Image
from scipy import ndimage
from sklearn.linear_model import LogisticRegression
from six.moves.urllib.request import urlretrieve
from six.moves import cPickle as pickle
%matplotlib inline
import scipy

In [2]:
display(Image(filename='notMNIST_small/A/MlRvb24yIFNoYWRvdy50dGY=.png'))

In [16]:
#os.listdir('notMNIST_small/B')

In [14]:
display(Image(filename='notMNIST_small/A/MTFTMDEgQmxhY2sgVHVlc2RheSBPZmZzZXQudHRm.png'))

In [17]:
imagefile = os.listdir('notMNIST_large/')
imagefile

['H', 'I', 'G', 'D', 'J', 'F', 'B', 'A.pickle', 'A', 'C', 'E']

In [18]:
len(imagefile)

11

In [22]:
dataset = np.ndarray(shape=(len(imagefile), 28, 28),
                         dtype=np.float32)
#dataset

In [32]:
np.ndarray(shape=(3,3,3),dtype=np.float32)

array([[[  1.29178753e+31,   4.55926468e-41,   3.24061996e-37],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00]],

       [[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00]],

       [[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00]]], dtype=float32)

In [51]:
for image in imagefile:
    image_file = os.path.join('notMNIST_large/',image)
    print(image_file)
  #  try:
   #     image_data = ((ndimage.imread(image_file).astype(float) - 
    #                255 / 2) / 255)

notMNIST_large/H
notMNIST_large/I
notMNIST_large/G
notMNIST_large/D
notMNIST_large/J
notMNIST_large/F
notMNIST_large/B
notMNIST_large/A.pickle
notMNIST_large/A
notMNIST_large/C
notMNIST_large/E


In [67]:
train_folders = ('notMNIST_large/')
test_folders = ('notMNIST_small/')
train_datasets = (train_folders,45000)
test_datasets = (test_folders,1800)

data_folders, min_num_images_per_class = train_datasets  

dataset_names = []
for folder in data_folders:
    set_filename = folder + '.pickle'
    dataset_names.append(set_filename)
    
dataset_names

['n.pickle',
 'o.pickle',
 't.pickle',
 'M.pickle',
 'N.pickle',
 'I.pickle',
 'S.pickle',
 'T.pickle',
 '_.pickle',
 'l.pickle',
 'a.pickle',
 'r.pickle',
 'g.pickle',
 'e.pickle',
 '/.pickle']

In [60]:
train_datasets,test_datasets

(('notMNIST_large/', 45000), ('notMNIST_small/', 1800))

In [12]:
valid_size = 10000
nb_rows = valid_size
img_size = 28

def make_arrays(nb_rows,img_size):
    if nb_rows:
        dataset = np.ndarray((nb_rows,img_size,img_size),dtype=np.float32)
        labels = np.ndarray(nb_rows,dtype=np.int32)
    else:
        dataset,labels = None,None
    return dataset,labels
#make_arrays(nb_rows,img_size)

In [22]:
labels = np.random.rand(10000)
labels.shape
datasets = np.random.rand(10000,28,28)
datasets.shape,labels.shape

((10000, 28, 28), (10000,))

In [26]:
permutation = np.random.permutation(labels.shape[0])
permutation.shape
shuffuled_dataset = datasets[permutation,:,:]
shuffuled_labels = labels[permutation]

In [31]:
img_data = (ndimage.imread('notMNIST_small/A/MDEtMDEtMDAudHRm.png').astype(float) - 255 /2) / 255

In [32]:
img_data.shape

(28, 28)

In [33]:
img_data

array([[-0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.45294118, -0.45686275, -0.49607843, -0.5       , -0.46470588,
        -0.48039216, -0.5       , -0.49607843, -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       ],
       [-0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.44117647, -0.40980392, -0.17843137, -0.04509804, -0.26078431,
        -0.15098039, -0.35882353, -0.5       , -0.49607843, -0.5       ,
        -0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       ],
       [-0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       , -0.49215686, -0.5       ,
        -0.2254902 ,  0.1196

In [59]:
img_data_flatten = (ndimage.imread('notMNIST_small/A/OEJhbGxTY3JpcHRTQ2Fwc1NTSyBJdGFsaWMudHRm.png'))

In [60]:
img_data_flatten.shape

(28, 28)

In [61]:
img_data_flatten_flat = img_data_flatten.flat

In [62]:
len(img_data_flatten_flat),len(img_data_flatten)

(784, 28)

In [66]:
small_img = (ndimage.imread('notMNIST_small/test/0.jpg',flatten=True))
small_img.shape

(5, 5)

In [67]:
small_img

array([[ 255.,  225.,  131.,  227.,  255.],
       [ 253.,   98.,  173.,   84.,  250.],
       [ 252.,   56.,  246.,   58.,  255.],
       [ 255.,   87.,  179.,   78.,  250.],
       [ 251.,  226.,  120.,  226.,  254.]], dtype=float32)

In [73]:
small_img_0_10 = (ndimage.imread('notMNIST_small/test/0_10.jpg',flatten=True))
small_img_0_10.shape

(10, 10)

In [71]:
small_img_0_10

array([[ 255.,  249.,  255.,  255.,  252.,  255.,  254.,  255.,  255.,
         255.],
       [ 254.,  255.,  255.,  141.,   22.,   13.,  141.,  255.,  255.,
         255.],
       [ 253.,  255.,  216.,    9.,  104.,  113.,    0.,  209.,  255.,
         255.],
       [ 255.,  255.,  145.,    0.,  227.,  233.,    4.,  142.,  255.,
         255.],
       [ 253.,  251.,  122.,    5.,  239.,  249.,    0.,  102.,  255.,
         255.],
       [ 254.,  255.,  117.,    3.,  242.,  251.,    5.,  115.,  255.,
         255.],
       [ 255.,  255.,  140.,    0.,  230.,  236.,    0.,  136.,  255.,
         255.],
       [ 255.,  251.,  206.,    4.,  124.,  129.,    5.,  200.,  255.,
         255.],
       [ 253.,  255.,  250.,  125.,    3.,    9.,  115.,  253.,  255.,
         255.],
       [ 255.,  252.,  255.,  253.,  245.,  249.,  250.,  255.,  255.,
         255.]], dtype=float32)

In [76]:
small_img_0_8 = (ndimage.imread('notMNIST_small/test/0_8.jpg',flatten=True))
small_img_0_8.shape

(8, 8)

In [77]:
small_img_0_8

array([[ 255.,  255.,  255.,  223.,  223.,  253.,  255.,  255.],
       [ 253.,  254.,  153.,   13.,   16.,  147.,  254.,  253.],
       [ 255.,  255.,   33.,  158.,  166.,   30.,  251.,  255.],
       [ 255.,  246.,    3.,  190.,  201.,    1.,  240.,  255.],
       [ 251.,  253.,    0.,  191.,  202.,    0.,  247.,  252.],
       [ 253.,  255.,   20.,  167.,  175.,   16.,  255.,  254.],
       [ 255.,  251.,  137.,   19.,   22.,  130.,  251.,  255.],
       [ 254.,  255.,  255.,  209.,  209.,  252.,  255.,  253.]], dtype=float32)

In [91]:
np.logical_and(small_img_0_8>170,small_img_0_8>40,dtype=int)

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True, False, False, False, False,  True,  True],
       [ True,  True, False, False, False, False,  True,  True],
       [ True,  True, False,  True,  True, False,  True,  True],
       [ True,  True, False,  True,  True, False,  True,  True],
       [ True,  True, False, False,  True, False,  True,  True],
       [ True,  True, False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]], dtype=bool)

In [82]:
x = np.arange(5)
np.logical_and(x>1,x<4)

array([False, False,  True,  True, False], dtype=bool)

In [95]:
(small_img_0_8 >100).astype(int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 1, 1, 1],
       [1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 1, 0, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [96]:
(small_img_0_10>100).astype(int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])